title: Matthew Tran's Blog!
description: Hi! I'm a human being who loves to learn new things and create cool projects.
repository: dragonlock2/dragonlock2.github.io
base_url: ""
url: "https://matthewtran.dev"
search: true

email: matthewlamtran@berkeley.edu
github_username: dragonlock2
linkedin_username: matthewlamtran

permalink: /:year/:month/:title/
show_excerpts: true

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: dark
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-paginate

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-WH7WNE01V5"
    anonymize_ip: false # default

paginate: 12
paginate_path: /page:num/

author:
  name: "Matthew Tran"
  avatar: "/assets/img/bio.jpg"
  bio: "Hi! I'm a human being who loves to learn new things and create cool projects."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dragonlock2"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matthewlamtran/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dragonlock2"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/matthewlamtran/"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
    label: "comment"

category_archive:
  type: liquid
  path: /categories/

lunr:
  search_within_pages: true

compress_html:
  clippings: all
